### ISSUE TITLE
"Start Administration Panel" fails with "{{'INDEX_BRAND' | translate}}"

### ISSUE THREAD

**Issue by imonk** [hrz-unimr/Ilias.RESTPlugin#15]
I was able to install & activate the plugin. I can open the info page (see attachment). Everything looks good but the REST/apps/admin/index.php seems to have trouble translating when I'm trying to open the Administration Panel.

<img width="400" alt="restplugin" src="https://cloud.githubusercontent.com/assets/156775/9385352/4e190c76-4756-11e5-9f5d-4b5f953257c7.png">

Error:
<img width="294" alt="rest2" src="https://cloud.githubusercontent.com/assets/156775/9385428/aad9f830-4756-11e5-8b77-05208a7f3bbe.png">

**Comment by Hufschmidt** [comment]
Thank you for your report.

The translation inside the admin-panel is done using AngularJS.
Is only the translation missing, or is the whole login/navigation panel missing/broken?

My first guess is, either the Angular plugin could not load/find the translations or Angular (as a whole) was unable to initialize for some reason.

Is there any output in the developer console when browsing the admin-panel?
 (In chrome: CTRL + SHIFT + I -> Console)

**Comment by imonk** [comment]
Thanks for the swift reply.

You're right, AngularJS is complaining that some  postVars is not defined in the module myApp.service (see console log below). 
Since the php fails on translating the index_title I don't get anything else of the RESTplugin admin panel than " {{'INDEX_BRAND' | translate}}". 
Within ILIAS everything seems to be fine, I have english & german language packages installed and can switch between them without problems.

Console error output:

Uncaught SyntaxError: Unexpected identifier
------------------------------------------------------
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module myApp.services due to:
ReferenceError: postVars is not defined
    at new <anonymous> (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/js/services.js:24:21)
    at invoke (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4464:17)
    at Object.instantiate (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4472:27)
    at provider (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4307:36)
    at Object.provider (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4299:16)
    at runInvokeQueue (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4370:35)
    at http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4378:11
    at forEach (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:336:20)
    at loadModules (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4360:5)
    at http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4377:40
http://errors.angularjs.org/1.4.4-build.4128+sha.e742316/$injector/modulerr…erInterfaceHook%2FREST%2Fapps%2Fadmin%2Flibs%2Fjs%2Fangular.js%3A4377%3A40
    at REGEX_STRING_REGEXP (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:68:12)
    at http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4399:15
    at forEach (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:336:20)
    at loadModules (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4360:5)
    at http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4377:40
    at forEach (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:336:20)
    at loadModules (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4360:5)
    at createInjector (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:4286:11)
    at doBootstrap (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:1649:20)
    at bootstrap (http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:1670:12)
http://errors.angularjs.org/1.4.4-build.4128+sha.e742316/$injector/modulerr…erInterfaceHook%2FREST%2Fapps%2Fadmin%2Flibs%2Fjs%2Fangular.js%3A1670%3A12)


REGEX_STRING_REGEXP	@	angular.js:68
(anonymous function)	@	angular.js:4399
forEach	@	angular.js:336
loadModules	@	angular.js:4360
createInjector	@	angular.js:4286
doBootstrap	@	angular.js:1649
bootstrap	@	angular.js:1670
angularInit	@	angular.js:1564
(anonymous function)	@	angular.js:28353
jQuery.Callbacks.fire	@	jquery.js:3094
jQuery.Callbacks.self.fireWith	@	jquery.js:3206
jQuery.extend.ready	@	jquery.js:3412
completed	@	jquery.js:3428

**Comment by Hufschmidt** [comment]
Could you try accessing the admin-panel by calling:

     .../restplugin.php/rest/config

restplugin.php is located inside your base ILIAS folder.

If this works than our "auto-login" Feature when coming from ILIAS is broken (again)...

**Comment by imonk** [comment]
I tried calling it directly but got back a 500 error. The permissions for restplugin.php are the same as for every other .php file in the ilias base folder

```
GET http://[myDomain]/ilias/restplugin.php/rest/config 500 (Internal Server Error)
Navigated to http://[myDomain]/ilias/restplugin.php/rest/config 					ilias/restplugin.php/:1 

GET http://[myDomain]/ilias/restplugin.php/ 500 (Internal Server Error)				ilias/restplugin.php
Navigated to http://[myDomain]/ilias/restplugin.php/
```

**Comment by imonk** [comment]
Th error.log states some invalid usage of $this when not in object context and an undefined constant ENT_HTML5:
```
[Fri Aug 21 13:58:26 2015] [error] [client 31.24.11.200] PHP Fatal error: Using $this when not in object context in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/app.php on line 89 
[Fri Aug 21 13:58:26 2015] [error] [client 31.24.11.200] PHP Fatal error: Using $this when not in object context in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/app.php on line 195 
[Fri Aug 21 13:58:49 2015] [error] [client 31.24.11.200] PHP Notice: Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5' in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php on line 40, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI 
[Fri Aug 21 13:58:49 2015] [error] [client 31.24.11.200] PHP Notice: Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5' in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php on line 41, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI 
[Fri Aug 21 13:58:49 2015] [error] [client 31.24.11.200] PHP Notice: Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5' in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php on line 42, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI 
[Fri Aug 21 13:58:49 2015] [error] [client 31.24.11.200] PHP Notice: Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5' in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php on line 43, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI 
[Fri Aug 21 13:58:49 2015] [error] [client 31.24.11.200] PHP Notice: Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5' in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php on line 44, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI 
[Fri Aug 21 13:58:49 2015] [error] [client 31.24.11.200] PHP Notice: Use of undefined constant ENT_HTML5 - assumed 'ENT_HTML5' in /var/www/vhosts/[...]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php on line 45, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI


```

**Comment by Hufschmidt** [comment]
Which PHP version is running on your server? We tested mostly against 5.6, although we also did some limited tests with 5.4.

**Comment by imonk** [comment]
Oh dear, we're still on  5.3.3. I probably should have mentioned earlier, sorry. 
I guess it's time to update...

**Comment by Hufschmidt** [comment]
I did a quick search and it seems like ENT_HTML5 constants where introduced in 5.4.
While those aren't strikely necessary, fixing the issue with $this is a bit more difficult/involved.
( Eg. http://stackoverflow.com/questions/8690557/refer-to-this-from-anonymous-function-inside-a-class-method )

You can try downloading the latest version with git (should fix ENT_HTML5 constants missing) and apply this patch afterwards: https://gist.github.com/Hufschmidt/70f07504fc30574ea01b

But I have a feeling this won't be the last problems we might stumble upon with 5.3.x...

**Comment by imonk** [comment]
Thanks for your effort. The new version complains differently when opening the Admin-Panel (with & without patch):
![restfail](https://cloud.githubusercontent.com/assets/156775/9444108/0d17f6e2-4a85-11e5-9451-84bb21c7c0bd.png)
Not sure about those double slashes... direct call of  .../ilias/restplugin.php/rest/config does't work either.

After patching the error.log doesn't complain anymore about the previous issues, but others:
```
[Mon Aug 24 17:33:56 2015] [error] [client 31.24.11.200] PHP Fatal error: Call to undefined function RESTController\\libs\\getallheaders() in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/libs/RESTRequest.php on line 23, referer: http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php 
[Mon Aug 24 17:33:56 2015] [error] [client 31.24.11.200] PHP Fatal error: Call to protected method RESTController\\RESTController::displayError() from context '' in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/app.php on line 198, referer: http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php 
[Mon Aug 24 17:34:07 2015] [error] [client 31.24.11.200] PHP Fatal error: Call to undefined function RESTController\\libs\\getallheaders() in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/libs/RESTRequest.php on line 23 
[Mon Aug 24 17:34:07 2015] [error] [client 31.24.11.200] PHP Fatal error: Call to protected method RESTController\\RESTController::displayError() from context '' in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/app.php on line 198 
[Mon Aug 24 17:35:42 2015] [error] [client 31.24.11.200] PHP Warning: require_once(Services/Init/classes/class.ilInitialisation.php): failed to open stream: No such file or directory in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/ilias.php on line 15, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI 
[Mon Aug 24 17:35:42 2015] [error] [client 31.24.11.200] PHP Fatal error: require_once(): Failed opening required 'Services/Init/classes/class.ilInitialisation.php' (include_path='.:') in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/ilias.php on line 15, referer: http://[myDomain]/ilias/ilias.php?ref_id=31&admin_mode=settings&ctype=Services&cname=UIComponent&slot_id=uihk&pname=REST&cmd=configure&cmdClass=ilrestconfiggui&cmdNode=rc:6s:uv&baseClass=ilAdministrationGUI 
[Mon Aug 24 17:37:10 2015] [error] [client 31.24.11.200] File does not exist: /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/routes, referer: http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php 
[Mon Aug 24 17:37:10 2015] [error] [client 31.24.11.200] PHP Fatal error: Call to undefined function RESTController\\libs\\getallheaders() in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/libs/RESTRequest.php on line 23, referer: http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php 
[Mon Aug 24 17:37:10 2015] [error] [client 31.24.11.200] PHP Fatal error: Call to protected method RESTController\\RESTController::displayError() from context '' in /var/www/vhosts/[myDomain]/subdomains/[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController/app.php on line 198, referer: http://[myDomain]/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/index.php
```

**Comment by imonk** [comment]
Just to let you know. I installed ILIAS 5.0.4 with PHP Version 5.5.26 on a VM and the control panel works flawlessly. 
It is yet another reason to update our productive Server in the near future. Thanks again for your help.

**Comment by Hufschmidt** [comment]
This is good to hear. :)

In the future we might do some further work on (sup)porting PHP 5.3.x (since it is currently the miniumal version required for ILIAS 5.0.x), but currently we are / I'm more focused at implementing a client-side application that consumes our REST-API.

I'll close this issue for now and add this to our internal task-tracker.

**Comment by Hufschmidt** [comment]
PS: Is there a way we could contact you. Although we are still relatively early in development we'd be interrested in feedback / your use-cases. (My contact: hufschmidt [@] hrz [.] uni-marburg [.] de)
