### ISSUE TITLE
Problems with (refresh-) tokens (and how they are transmitted)

### ISSUE THREAD

**Issue by Hufschmidt** [hrz-unimr/Ilias.RESTPlugin#18]
There seem to be multiple issues with (refresh-)tokens...

Issue 1: (By example)
The refresh-token inside database is:

    NixhcG9sbG9uLHJlZnJlc2gsMHhXeVIsMTQ0MTA5NDYzNix5aDNFQjBsam1HYnVlN1dFWjQxdHRDWXZBLDA5ZjU4ZGI2ODdjZDlkNjM0NGY4Yjc5YjAyMjQ2ODlhNWM4NWVjMmNmMmEzNDVlNDdlNmYyYjRmZDljMDVhODQ%3D

The refresh-key recieved when talking to /v1/oauth2/token endpoint with { grant_type: 'password', username:   '...', password:   '...', api_key:   '...' } is:

    NixhcG9sbG9uLHJlZnJlc2gsMHhXeVIsMTQ0MTA5NDYzNix5aDNFQjBsam1HYnVlN1dFWjQxdHRDWXZBLDA5ZjU4ZGI2ODdjZDlkNjM0NGY4Yjc5YjAyMjQ2ODlhNWM4NWVjMmNmMmEzNDVlNDdlNmYyYjRmZDljMDVhODQ%3D%3D

Notice the last %3d. This could be an encoding issue when transforming sql-result to json. (See core->auth->models->Token->Generic->serializeToken(...) ?)

Issue 2:
Get remaing refresh returns null because of issue 1 and because $refreshToken->getUserId() in core->auth->models -> RefreshEndpoints -> getRemainingRefreshs(...) returns null.

The later happens because the user-entry in $refreshToken object is numeric (should be actual user-NAME).
Either the refresh-token is accidently build by using a userId instead of userName (bug!) or this is a decoding bug related to issue 1.
(See core->auth->models->RefreshEndpoint->getToken(...))

Should be easy to fix. :)

**Comment by eqsoft** [comment]
Hallo Thomas,
scheint ein base64 Encodig Problem zu sein (%3D ist urlencoded "=" character):
https://de.wikipedia.org/wiki/Base64:

"Falls die Gesamtanzahl der Eingabebytes nicht durch drei teilbar ist, wird der zu kodierende Text am Ende mit aus Nullbits bestehenden Füllbytes aufgefüllt, so dass sich eine durch drei teilbare Anzahl an Bytes ergibt. Um dem Dekodierer mitzuteilen, wie viele Füllbytes angefügt wurden, werden die 6-Bit-Blöcke, die vollständig aus Füllbytes entstanden sind, mit = kodiert. Somit können am Ende einer Base64-kodierten Datei null, ein oder zwei =-Zeichen auftreten. Anders gesagt, es werden so viele =-Zeichen angehängt, wie Füllbytes angefügt worden sind."

Lg,
Stefan
