### ISSUE TITLE
tiny typo in ilias-shell readme.txt

### ISSUE THREAD

**Issue by imonk** [hrz-unimr/Ilias.RESTPlugin#22]
The last line in the readme.txt has a typo in the last key value pair:
{'login':'isabell','passwd':'top_secret','firstname':'isa','lastname':'bell','email':'testing@localhost','gender','f'})
should be
{'login':'isabell','passwd':'top_secret','firstname':'isa','lastname':'bell','email':'testing@localhost','gender':'f'})

colon instead of komma.

Otherwise works like a charm, even on mac;)

P.S. The install note could also mention the pip way (which *should* be platform independent)

pip install ipython
pip install poster

**Comment by Hufschmidt** [comment]
Thanks for the hint, I'll try to fix/update the readme once I can make some spare time. :)

**Comment by Hufschmidt** [comment]
Fixed in current dev-branch. 
(which is not quite ready for production yet, as the admin-panel needs to be updated)
