### ISSUE TITLE
Managing routs & basic settings fails with  401 (Unauthorized)

### ISSUE THREAD

**Issue by imonk** [hrz-unimr/Ilias.RESTPlugin#28]
Hello,

To exlude side effects from our dev-environment I just installed a fresh IILIAS v5.1.5 with PHP 5.6.20, copied the latest RESTplugin and gave permissions to read,write and execute all ILIAS & log file paths. The Plugin installs and activates fine, but the Browser console complains when opening "Manage API-Keys and Authorization Schemes":

`angular.js:10541 GET http://<<host.name>>/ILIAS/v2/util/routes 404 (Not Found)(anonymous function) @ angular.js:10541sendReq @ angular.js:10360serverRequest @ angular.js:10072processQueue @ angular.js:14523(anonymous function) @ angular.js:14539Scope.$eval @ angular.js:15802Scope.$digest @ angular.js:15613Scope.$apply @ angular.js:15910bootstrapApply @ angular.js:1652invoke @ angular.js:4464doBootstrap @ angular.js:1650bootstrap @ angular.js:1670angularInit @ angular.js:1564(anonymous function) @ angular.js:28353fire @ jquery.js:3094self.fireWith @ jquery.js:3206jQuery.extend.ready @ jquery.js:3412completed @ jquery.js:3428
angular.js:10541 GET http://<<host.name>>/ILIAS/restplugin.php/v1/clients 401 (Unauthorized)(anonymous function) @ angular.js:10541sendReq @ angular.js:10360serverRequest @ angular.js:10072processQueue @ angular.js:14523(anonymous function) @ angular.js:14539Scope.$eval @ angular.js:15802Scope.$digest @ angular.js:15613Scope.$apply @ angular.js:15910done @ angular.js:10391completeRequest @ angular.js:10563requestLoaded @ angular.js:10504
angular.js:12285 Error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html
http://errors.angularjs.org/1.4.4-build.4128+sha.e742316/$sce/itype?p0=html
    at http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:68:12
    at trustAs (http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:16582:15)
    at Object.sce.(anonymous function) [as trustAsHtml] (http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:17333:16)
    at http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/js/filters.js:27:26
    at http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/js/controllers.js:144:53
    at http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UICo…onent/UserInterfaceHook/REST/apps/admin/libs/js/angular-resource.js:620:30
    at processQueue (http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:14523:28)
    at http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:14539:27
    at Scope.$eval (http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:15802:28)
    at Scope.$digest (http://<<host.name>>/ILIAS/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/admin/libs/js/angular.js:15613:31)`

When trying to set a logging path to enable logging in the Basic Settings, console outputs:

`angular.js:10541 PUT http://<<host.name>>/ILIAS/restplugin.php/v2/admin/config/rest_log 401 (Unauthorized)(anonymous function) @ angular.js:10541sendReq @ angular.js:10360serverRequest @ angular.js:10072processQueue @ angular.js:14523(anonymous function) @ angular.js:14539Scope.$eval @ angular.js:15802Scope.$digest @ angular.js:15613Scope.$apply @ angular.js:15910(anonymous function) @ angular.js:23297jQuery.event.dispatch @ jquery.js:4430elemData.handle @ jquery.js:4116
controllers.js:605 Config could NOT be saved! {"data":{"message":"Could not find any Access-Token in header, GET or POST (JSON/x-www-form-urlencoded) parameters.","status":"RESTController\\libs\\RESTRequest::ID_NO_TOKEN","data":{"type":"Access-Token"}},"status":401,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"headers":{"Authorization":"Bearer NixpbGlhc0RldixhcG9sbG9uLGFjY2VzcywsLDE0NjE2ODE0MzEsVzU2Nm9wZWVBZkY4b1ljVEdFamRYQWcydiw1MzA1ZWNiMDVlYWU0NjQyMjE0NWQxZjIwYmQ1MjRlMTVmNmUwZjEyNWExMGJkNTdlN2YyZTY4YWQ1ODI5MGE1","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"data":{"value":"/var/www/vhosts/<<host.name>>/web_users/iliasuser/logs/iliasplugin.log"},"url":"/ILIAS/restplugin.php/v2/admin/config/rest_log","cached":false},"statusText":"Unauthorized"}
angular.js:10541 PUT http://<<host.name>>/ILIAS/restplugin.php/v2/admin/config/access_token_ttl 401 (Unauthorized)(anonymous function) @ angular.js:10541sendReq @ angular.js:10360serverRequest @ angular.js:10072processQueue @ angular.js:14523(anonymous function) @ angular.js:14539Scope.$eval @ angular.js:15802Scope.$digest @ angular.js:15613Scope.$apply @ angular.js:15910(anonymous function) @ angular.js:23297jQuery.event.dispatch @ jquery.js:4430elemData.handle @ jquery.js:4116
controllers.js:621 Config could NOT be saved! {"data":{"message":"Could not find any Access-Token in header, GET or POST (JSON/x-www-form-urlencoded) parameters.","status":"RESTController\\libs\\RESTRequest::ID_NO_TOKEN","data":{"type":"Access-Token"}},"status":401,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"headers":{"Authorization":"Bearer NixpbGlhc0RldixhcG9sbG9uLGFjY2VzcywsLDE0NjE2ODE0MzEsVzU2Nm9wZWVBZkY4b1ljVEdFamRYQWcydiw1MzA1ZWNiMDVlYWU0NjQyMjE0NWQxZjIwYmQ1MjRlMTVmNmUwZjEyNWExMGJkNTdlN2YyZTY4YWQ1ODI5MGE1","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"data":{},"url":"/ILIAS/restplugin.php/v2/admin/config/access_token_ttl","cached":false},"statusText":"Unauthorized"}
angular.js:10541 PUT http://<<host.name>>/ILIAS/restplugin.php/v2/admin/config/refresh_token_ttl 401 (Unauthorized)(anonymous function) @ angular.js:10541sendReq @ angular.js:10360serverRequest @ angular.js:10072processQueue @ angular.js:14523(anonymous function) @ angular.js:14539Scope.$eval @ angular.js:15802Scope.$digest @ angular.js:15613Scope.$apply @ angular.js:15910(anonymous function) @ angular.js:23297jQuery.event.dispatch @ jquery.js:4430elemData.handle @ jquery.js:4116
controllers.js:637 Config could NOT be saved! {"data":{"message":"Could not find any Access-Token in header, GET or POST (JSON/x-www-form-urlencoded) parameters.","status":"RESTController\\libs\\RESTRequest::ID_NO_TOKEN","data":{"type":"Access-Token"}},"status":401,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"headers":{"Authorization":"Bearer NixpbGlhc0RldixhcG9sbG9uLGFjY2VzcywsLDE0NjE2ODE0MzEsVzU2Nm9wZWVBZkY4b1ljVEdFamRYQWcydiw1MzA1ZWNiMDVlYWU0NjQyMjE0NWQxZjIwYmQ1MjRlMTVmNmUwZjEyNWExMGJkNTdlN2YyZTY4YWQ1ODI5MGE1","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"data":{},"url":"/ILIAS/restplugin.php/v2/admin/config/refresh_token_ttl","cached":false},"statusText":"Unauthorized"}
angular.js:10541 PUT http://<<host.name>>/ILIAS/restplugin.php/v2/admin/config/salt 401 (Unauthorized)(anonymous function) @ angular.js:10541sendReq @ angular.js:10360serverRequest @ angular.js:10072processQueue @ angular.js:14523(anonymous function) @ angular.js:14539Scope.$eval @ angular.js:15802Scope.$digest @ angular.js:15613Scope.$apply @ angular.js:15910(anonymous function) @ angular.js:23297jQuery.event.dispatch @ jquery.js:4430elemData.handle @ jquery.js:4116
controllers.js:653 Config could NOT be saved! {"data":{"message":"Could not find any Access-Token in header, GET or POST (JSON/x-www-form-urlencoded) parameters.","status":"RESTController\\libs\\RESTRequest::ID_NO_TOKEN","data":{"type":"Access-Token"}},"status":401,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"headers":{"Authorization":"Bearer NixpbGlhc0RldixhcG9sbG9uLGFjY2VzcywsLDE0NjE2ODE0MzEsVzU2Nm9wZWVBZkY4b1ljVEdFamRYQWcydiw1MzA1ZWNiMDVlYWU0NjQyMjE0NWQxZjIwYmQ1MjRlMTVmNmUwZjEyNWExMGJkNTdlN2YyZTY4YWQ1ODI5MGE1","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"data":{},"url":"/ILIAS/restplugin.php/v2/admin/config/salt","cached":false},"statusText":"Unauthorized"}`

When debugging I found that in the RESTRequest class     
```
// Fetch 'access_token' from header, GET or POST...
        $tokenString = $this->params('access_token');
```
GET and POST are both empty arrays and tokenString stays empty until the end resulting in 

`X-Powered-By: PHP/5.6.20 Status: 401 Unauthorized Content-Type: application/json Www-Authenticate: Bearer realm="develop.ioneaccess.ch" {"message":"Could not find any Access-Token in header, GET or POST (JSON\/x-www-form-urlencoded) parameters.","status":"RESTController\\libs\\RESTRequest::ID_NO_TOKEN","data":{"type":"Access-Token"}}` 

Since this seems rather severe, in case that's not a known issue, could you try to reproduce it?

Thanks
-Torsten

**Comment by disc5** [comment]
Thank you for the issue report.

I tried to reproduce the problem with the following setup:
 IILIAS v5.1.5, PHP 5.6.17, Debian Jessie 3.16.0, i.e. in terms of ILIAS and PHP it is close to your setting. Furthermore I used Google Chrome Developer 52.0.2717.0 canary (64-bit) under Windows.

I encountered the following problem when installing the plugin for the first time:
implode error at dbupdate step 6.This can easily fixed by setting $id     = 1; and by omitting the initial select query at the beginning. This problem will be resolved in the next commit shortly.

Everything worked just fine then. This means I could not reproduce the original problem you posted.
Let's check some arguments:
- Did you put the restplugin.php at the webroot?
- Did you clean the cache of your browser? 
- Did you reinstall the plugin manually by following the instructions under "reset  of the plugin" in the wiki using the sql statements?

**Comment by imonk** [comment]
Hi Dirk,

thank you for your effort. It seems the cause narrows down to somewhere in the PLESK-way of serving CentOS 7... 

I found & solved the activation problem as described in my #27 reply and can confirm the 3 points you mentioned. Concerning the empty `GET` Variables, is this normal behaviour?

![debug](https://cloud.githubusercontent.com/assets/156775/14852060/5605bd8c-0c84-11e6-86d8-cdcd5c33688f.png)

There is a "token" in the HTTP_RAW_POST_DATA however when entering restplugin.php, but it's not found by the `getToken` method.

**Comment by Hufschmidt** [comment]
Are you using Apache with mod_proxy_fcgi and PHP5-FPM? If so add

    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

to you apache vhost. (mod_proxy_fcgi does not pass sensitive auth headers to php)

**Comment by imonk** [comment]
Yeah, das wars! 
Thanks heaps for this crucial hint! Works flawless now.
