### ISSUE TITLE
Boolean Type in DBUpdate will crash in ILIAS 5.2

### ISSUE THREAD

**Issue by otruffer** [hrz-unimr/Ilias.RESTPlugin#31]
Hi There

When installing the REST plugin for the latest trunk version the DB update steps will not work. This is due to a stricter handling of boolean types with the new DB layer. While up to now "boolean" was officially not supported by ILIAS (see: http://www.ilias.de/docu/goto_docu_pg_25354_42.html) the DB abstraction layer did not throw an exception (it added an error string that was displayed nowhere...). The new layer coming in 5.2 will throw an exception: "Invalid column type 'boolean Use integer(1) instead." 

I unfortunately cannot send you a pull request easily as we changed the folder structure in our fork. But if you change e.g.

    'grant_authorization_code' => array(
      'type'    => 'boolean'
    ),
to

    'grant_authorization_code' => array(
        'type'    => 'integer',
        'length'  => 1,
    ),

you should be fine.

**Comment by Hufschmidt** [comment]
Thank you, I'll merge this as soon I have some time to spare.
