### ISSUE TITLE
Site with routes down

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#32]
Hello,
The site http://api.myilias.edu/routes is not available since a few weeks at least.

Kind regards
Bastian

**Comment by Hufschmidt** [comment]
Hello Bastian,

thank you for using our RESTPlugin. In regards to the given URL, http://api.myilias.edu/v2/util/routes was more or less meant as an example, there is no website at this address. ;)

I'll will however update the WIKI with additional information and changes made to the RESTPlugin.
There will also be a major update to the RESTPlugin in the coming week, hopefully...

BR
Thomas

**Comment by bastianleirpo** [comment]
That sounds great! 
Greetings from Dortmund to Marburg.

Bastian

**Comment by Hufschmidt** [comment]
I somehow managed to scratch together a bit of free time to finally apply the most important updates to the documentation. There is still some documentation missing, especially regarding Content-Type support and handling...

I'll close this issue and open another one for this, see #37.
