### ISSUE TITLE
dbsetup crash on empty length for integer fields

### ISSUE THREAD

**Issue by eqsoft** [hrz-unimr/Ilias.RESTPlugin#33]
$ilDB->createTable('ui_uihk_rest_client', $fields, true);
crashes because of empty length for integer fields, p.e.:
    'grant_client_credentials' => array(
      'type'    => 'integer'
    ), 

after adding length attribute for all integer fields it works:
 'grant_client_credentials' => array(
      'type'    => 'integer',
      'length'  => 1
    ),
....
....

**Comment by Hufschmidt** [comment]
Thanks for pointing this out, fixed this sloppy oversight in version 1.6.1.
