### ISSUE TITLE
Unable to Login and REST endpoint not found error on php5.5.9, Ilias5.1.10

### ISSUE THREAD

**Issue by ni3keswani** [hrz-unimr/Ilias.RESTPlugin#34]
Unable to Login and REST endpoint not found error on php5.5.9, Ilias5.1.10
RestPlugin1.5.2
![ilias error](https://cloud.githubusercontent.com/assets/3282468/19759236/a39e9d66-9c49-11e6-9d5a-0ef05c877919.png)

**Comment by bastianleirpo** [comment]
If you have set up the path correctly (Issue #35) you need to place the api.php in the root directory and rename it to restplugin.php
That should solve the problem

**Comment by bastianleirpo** [comment]
But even then you can't access the restplugin.php file because of errors. What a messy release!

**Comment by Hufschmidt** [comment]
In my limited time rush to release 1.6.0 I totally forgot to fix the checkout app for the breaking changes that would be introduced by this release.
I've now both updated the admin-app as well as the checkout-app with additional improvements, both should work as intended now and give better feedback IFF the restplugin isn't working as intended. :beetle:
