### ISSUE TITLE
Path to plugin directory not set

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#38]
In RESTController.php (126) the variable $appDirectory is not set.

**Comment by bastianleirpo** [comment]
Solved it this way:
api.php:
```
$pluginRoot = $directory.'Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/RESTController';
$restCTL = new \RESTController\RESTController($directory,$pluginRoot);
```
In the RESTController constructor i use the $pluginRoot for setting the template in line 125:
`$this->view()->setTemplatesDirectory($pluginRoot);`

**Comment by Hufschmidt** [comment]
Thanks for pointing his out. I dropped $appDirectory and any related value, since it is not really needed any more...
