### ISSUE TITLE
Undefined $tokenString

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#39]
The method `$request->getToken('access', true);` throws an error because `$tokenString` is undefined in REST\RESTController\libs\RESTRequest.php line 251. 

I use ILIAS version 5.1.11 and route:
`Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/api.php/v2/oauth2/authorize?api_key=THE_KEY&redirect_uri=THE_URI&response_type=code`

The error is just displayed when i set `error_reporting` to `error_reporting(E_ALL);`

**Comment by Hufschmidt** [comment]
Again, thanks for pointing this one our, I had allready fixed this at home, but not commited to any repo, so it was missing in my workplace, hope I can prevent some of those erros with #41...
