### ISSUE TITLE
Loginscreen isn't displayed

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#40]
I use the route
`Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/api.php/v2/oauth2/authorize?api_key=THE_KEY&redirect_uri=THE_URI&response_type=code`. 

My REST client looks like this:

```
{
    api_key: "THE_KEY",
    client_credentials_userid: 6,
    grant_client_credentials: true,
    grant_authorization_code: true,
    grant_implicit: true,
    grant_resource_owner: true,
    refresh_authorization_code: true,
    refresh_resource_owner: true,
    users: "6",
    description: ""
}
```

If i add a `die();` after line 58 `Authorize::showWebsite($app, $data);` in OAuth2.php the login screen is displayed, otherwise not. 

If i hit "login" with the correct credentials, again a white page (no content) is displayed. GoogleChrome tells me: "Failed to load response data" in the developers network tab.

Do you have any suggestions?

Kind regards 
Bastian

**Comment by Hufschmidt** [comment]
This is a problem with the way I wrapped the Slim-Frameworks Request-Class to handle xml and json output. I have fixed this locally and should be able to push this fix today.
