### ISSUE TITLE
Exception: Assigning the return value of new by reference is deprecated

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#46]
Exception thrown in file "Rest\RESTController\extensions\users_v1\models\UsersModel.php", line 78 with route "/v1/users": Assigning the return value of new by reference is deprecated
Just remove the ampersand solved the issue.

**Comment by Hufschmidt** [comment]
Thanks for catching this. Most of the extension routes (with the exception of umr) where writen before my time and would really need a lift-up in implementation, documentation and some cleaning.

I think I fixed most of the reference-access modifier occurances...
