### ISSUE TITLE
Exception types not available

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#49]
Hello,

i saw that the class "Libs\Exceptions\ReadFailed" isn't available in the sources anymore, although there are references to the class. I found the class as a file in the REST-plugin v. 1.1.0.

Kind regards
Bastian

**Comment by Hufschmidt** [comment]
Should be fixed with 765ed811701e1f423df21bfd1b5b1bf6cf0babd0, those extensions are in dire need of rewrite/refactoring though...
