### ISSUE TITLE
Getting 404 on all endpoints with Postman

### ISSUE THREAD

**Issue by mraak** [hrz-unimr/Ilias.RESTPlugin#53]
I followed the install instructions and activated the plugin through administration. Some endpoints worked with internal testing app when clicking "Enter Checkout App" in the administration panel.

http://localhost/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/REST/apps/checkout/index.php?api_keys=apollon#/checkout

But then there's a lacking and conflicting info on what to do next. I was trying some of endpoints by Postman app and got 404 on all of them. Like for example:

http://localhost/ilias/v2/admin/permissions/:1
http://localhost/ilias/api/v2/admin/permissions/:1
http://localhost/ilias/api/v1/admin/permissions/:1
http://localhost/ilias/api/admin/permissions/:1

I tried dozens more, including the oauth ones, but 404 on all of them.

Could you add an example how to use the API's with Postman or other client, and what endpoints are there? Thanks.

**Comment by Hufschmidt** [comment]
Make sure to pass parameters without colons, eg. `http://localhost/.../api.php/v2/admin/permissions/1`.

Also some routes might require to use HTTP-PUT, HTTP-POST or even HTTP-DELETE and some require to pass a valid access-token (which for sake of easy is handled by the checkout-app), eg. as header: "Authorization: bearer <access-token>" which you get for example via [POST] `http://localhost/.../api.php/v2/oauth2/token`.

I hope this introduction will become easier once I implement #37
