### ISSUE TITLE
Sending zipped SCORM packages is working?

### ISSUE THREAD

**Issue by mraak** [hrz-unimr/Ilias.RESTPlugin#54]
I wonder if I could use this plugin to upload zipped SCORM packages to Ilias. Is this supported?

**Comment by Hufschmidt** [comment]
If this functionality exists with SOAP, there is a good chance that we mirrored this functionality, although I don't think this exists in SOAP.

I quickly glanced over our routes and nothing poked out in this regards. As far as I can see there are no API-Endpoints in regards to learning modules.

**Comment by Hufschmidt** [comment]
Putting this on hold because I do like the idea, but there is currently no work-quota for feature development.
