### ISSUE TITLE
ILIAS 5.2 compability

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#55]
ILIAS 5.2 changed a lot its internal structure according authentication. Therefore the RESTPlugin doesn't work anymore in context of bridging: RESTPlugin -> Login into ILIAS.
`lPDOAuthentication::setAuth()` is a private method now. The error occurred in: RESTController\libs\RESTilias:372

Kind regards
bastianleirpo

**Comment by Hufschmidt** [comment]
I'll most likely not find any free time during work to look into this, but since 5.2 is getting more popular I'll look into this and will implement real support for 5.2.

Sorry if the `ilias_max_version` value might have been misleading here...

**Comment by Hufschmidt** [comment]
The following commits should add support for ILIAS 5.2, at least for the REST-Plugin core, without proper automated test for the extensions its hard to say what might have broken between updates.

Related commits:
1f2e9c0aed531f7751d8f702ebdc32b8b8f75e61
2ce12f56ab13a99922b001d1713f5dc08fd17704
df69fc0e25b4aebe4d037eb319337b6b69e48f97
