### ISSUE TITLE
CoursesModel throws exceptions on ILIAS 5.2 because of non-existing files

### ISSUE THREAD

**Issue by mat178** [hrz-unimr/Ilias.RESTPlugin#56]
https://github.com/hrz-unimr/Ilias.RESTPlugin/blob/aa403ecb9fdd11e2e096f62deab3c83fec9d1b53/RESTController/extensions/courses_v1/models/CoursesModel.php#L20

https://github.com/hrz-unimr/Ilias.RESTPlugin/blob/aa403ecb9fdd11e2e096f62deab3c83fec9d1b53/RESTController/extensions/courses_v1/models/CoursesModel.php#L21

both lines throw exceptions because corresponding files were moved or don't exist anymore in ILIAS 5.2

**Comment by Hufschmidt** [comment]
Thank you. Has been fixed by [studer + raimann ag](https://github.com/studer-raimann/Ilias.RESTPlugin) and merged into master.
